### PR TITLE
Update maximum PHP dependency in composer.json

### PR DESCRIPTION
**Pull request by adamroyle**
Can you please tag a 2.0.1 release?

### CODE REVIEW

**Comment by nateabele** [comment]
Yeah, I'd just like to get _some_ sort of automated verification in place for this stuff before pushing any more releases. Do you happen to know of any decent GHA templates for this off-hand?

**Comment by adamroyle** [comment]
Maybe something like this?


https://github.com/ElephantIO/elephant.io/blob/master/.github/workflows/continuous-integration.yml


I’m not sure about the dependencies required to run the lithium test suite as I had
issues getting it to run locally.

**Comment by nateabele** [comment]
> https://github.com/ElephantIO/elephant.io/blob/master/.github/workflows/continuous-integration.yml

Yeah that looks about right, thanks. I'll give it a try tomorrow or Monday.

> I’m not sure about the dependencies required to run the lithium test suite as I had issues getting it to run locally.

Oh, which ones? Just curious.

**Comment by adamroyle** [comment]
I think I'm just unfamiliar with the process of running the lithium tests properly. I managed to get the devcontainer running by changing `mysql:5` to `mysql:8.0` but I'm a little confused how to get the tests running.

**Comment by nateabele** [comment]
I haven't had time to finish setting up the tests so I'm just gonna ship this. Let me know if you run into any issues (I think we're good re: compatibility though).

**Pull request merged**
