### PR TITLE
Fix bug #1365 Model::find() returns false instead of empty RecordSet

### PR DESCRIPTION
**Pull request by adamroyle**

### CODE REVIEW

**Comment by nateabele** [comment]
Looks good, thanks! I'll figure out why the container build is failing and get this merged in. Looks like just a permissions issue.

**Comment by nateabele** [comment]
(For my own reference: https://github.com/actions/runner/issues/1039)

**Comment by adamroyle** [comment]
Should I recreate the PR on 2.0 branch rather than this branch?

**Comment by nateabele** [comment]
Oh, yes, please. I didn't realize it wasn't already.

**Pull request closed without merging**
