### PR TITLE
Happy 2016

### PR DESCRIPTION
**Pull request by mohnjatthews**
Simply changing the copyright year from 2015 to 2016.

### CODE REVIEW

**Comment by shopblocks** [comment]
https://github.com/UnionOfRAD/lithium/issues/1254

**Comment by davidpersson** [comment]
@mohnjatthews There are many more occurrences. We are also in the process of determining if we want to update the year at all, each time a new one arrives.

**Comment by mohnjatthews** [comment]
Oops, my bad. Didn't see the previous pull request. Won't happen again.

**Comment by davidpersson** [comment]
nvm

**Pull request closed without merging**
