### PR TITLE
Dont load the String class if you are in PHP 7+

### PR DESCRIPTION
**Pull request by shopblocks**

### CODE REVIEW

**Comment by shopblocks** [comment]
Locally, I get a segmentation fault, being caused by the `testDeprecatedInit()` method in `LibrariesTest.php`

It is calling `MockInitMethod::li3()`.

If i place a `trigger_error('Deprecated', E_USER_DEPRECATED);` in there, it passes fine, without any segmentation faults.

Not sure what the cause of all of this is, but it perhaps needs looking into a bit deeper. May be an issue with the PPA im using for PHP 7, but its the best one available for Ubuntu 14.04 64-bit.

**Comment by shopblocks** [comment]
@davidpersson Are you able to explain what this test should be doing?

```php
public function testDeprectatedInit() {
		$this->assertException("/Deprecated/", function() {
			MockInitMethod::li3();
		});
	}
```

It is causing a segmentation fault in my version, but i can't see what would be wrong. Thanks.

**Comment by nateabele** [comment]
This seems like a really hacky approach. Where is `String` getting loaded from.

**Comment by shopblocks** [comment]
@nateabele Its being loaded because it calls a:

```php
$classes = Libraries::find(true, compact('exclude') + array('recursive' => true));
```

in Affected.php:84.

**Comment by shopblocks** [comment]
I agree to it being hacky, but it is all I could get to work, either that or delete the file outright.

**Comment by shopblocks** [comment]
@nateabele You can see some more details in this thread: https://github.com/UnionOfRAD/lithium/issues/1224

**Comment by nateabele** [comment]
Why not have `Affected` filter out deprecated classes by default?

**Comment by shopblocks** [comment]
This would still cause issues anywhere else that does Libraries::find(true).

This way, it will never cause errors because it will never be loaded.

**Comment by alexbowers** [comment]
Alternative implementation @nateabele https://github.com/UnionOfRAD/lithium/pull/1238

**Pull request closed without merging**
